FROM bcit/alpine:3.10
<%= snippet('labels', binding) -%>

RUN apk add --no-cache \
    python3=<%= image.labels['python_version'] %>-r<%= image.labels['python_apk_release'] %> \
    py3-pip

RUN pip3 install --upgrade pip

COPY smoketest.py /smoketest.py
ENTRYPOINT ["/sbin/tini", "--", "/docker-entrypoint.sh", "python3"]
