FROM bcit/alpine:3.10

LABEL maintainer="<%= maintainer %>"
LABEL version="<%= version %>"

ENV VERSION "<%= version %>"

RUN apk add --no-cache \
    python3=<%= version %> \
    py3-pip

RUN pip3 install --upgrade pip


ENTRYPOINT ["/sbin/tini", "--", "/docker-entrypoint.sh"]

CMD ["python3"]
